import * as stylex from "@stylexjs/stylex";
import { accents, colors, motion, typography } from "../../styles/tokens.stylex";

const fadeIn = stylex.keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 },
});

const savePulse = stylex.keyframes({
  "50%": { opacity: 0.45, transform: "scale(0.82)" },
});

const loadingSpin = stylex.keyframes({
  to: { transform: "rotate(360deg)" },
});

export const editorStyles = stylex.create({
  fallback: {
    display: "grid",
    minHeight: 0,
    minWidth: 0,
    placeItems: "center",
    backgroundColor: colors.canvas,
    color: colors.muted,
    fontSize: "14px",
  },
  workspace: {
    display: "grid",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    gridTemplateRows: "56px 42px minmax(0, 1fr)",
    backgroundColor: colors.canvas,
  },
  header: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    justifyContent: "space-between",
    paddingInline: "16px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundColor: `color-mix(in srgb, ${colors.elevated} 68%, ${colors.canvas})`,
    backdropFilter: "blur(14px)",
  },
  minWidth: { minWidth: 0 },
  title: {
    overflow: "hidden",
    color: colors.text,
    fontSize: "14px",
    fontWeight: 600,
    letterSpacing: 0,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  subtitle: {
    overflow: "hidden",
    marginTop: "2px",
    color: colors.muted,
    fontSize: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  saveDot: {
    display: "block",
    width: "7px",
    height: "7px",
    flex: "none",
    marginRight: "4px",
    borderRadius: "999px",
    backgroundColor: "#5ca878",
    boxShadow: "0 0 0 2px color-mix(in srgb, #5ca878 14%, transparent)",
    transitionProperty: "background-color, box-shadow",
    transitionDuration: motion.standard,
    transitionTimingFunction: "ease",
  },
  saveDotDirty: {
    backgroundColor: colors.danger,
    boxShadow: `0 0 0 2px color-mix(in srgb, ${colors.danger} 14%, transparent)`,
  },
  saveDotSaving: {
    backgroundColor: accents.primary,
    boxShadow: `0 0 0 2px color-mix(in srgb, ${accents.primary} 16%, transparent)`,
    animationName: {
      default: savePulse,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: "1.1s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  viewSwitcher: {
    display: "flex",
    alignItems: "center",
    padding: "2px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${colors.border} 88%, transparent)`,
    borderRadius: "8px",
    backgroundColor: `color-mix(in srgb, ${colors.panel} 74%, transparent)`,
  },
  viewButton: {
    width: "27px",
    height: "25px",
    borderRadius: "6px",
    transitionDuration: {
      default: "150ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  },
  viewButtonActive: {
    backgroundColor: colors.elevated,
    color: colors.text,
    boxShadow: "0 1px 2px rgb(35 33 29 / 10%), inset 0 0 0 1px rgb(255 255 255 / 46%)",
  },
  iconSmall: { width: "14px", height: "14px" },
  icon: { width: "16px", height: "16px" },
  favoriteIcon: {
    width: "16px",
    height: "16px",
    transitionProperty: "color, fill",
    transitionDuration: "150ms",
  },
  favoriteIconActive: { fill: accents.primary },
  mobileHidden: {
    display: {
      default: "inline-flex",
      "@media (max-width: 760px)": "none",
    },
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    overflowX: "auto",
    paddingInline: "14px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundColor: `color-mix(in srgb, ${colors.elevated} 76%, ${colors.canvas})`,
    scrollbarWidth: "thin",
  },
  toolbarGroup: {
    display: "flex",
    alignItems: "center",
  },
  toolbarDivider: {
    marginLeft: "4px",
    paddingLeft: "4px",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: `color-mix(in srgb, ${colors.border} 82%, transparent)`,
  },
  formatButton: {
    width: "29px",
    height: "29px",
    borderRadius: "6px",
  },
  formatMenuButton: {
    width: "38px",
    gap: "1px",
  },
  chevronIcon: {
    width: "10px",
    height: "10px",
  },
  empty: {
    display: "grid",
    placeItems: "center",
    padding: "24px",
    textAlign: "center",
  },
  emptyTitle: {
    color: colors.text,
    fontSize: "18px",
    fontWeight: 700,
  },
  emptyBody: {
    marginTop: "8px",
    color: colors.muted,
    fontSize: "14px",
  },
  emptyLoadingIcon: {
    width: "20px",
    height: "20px",
    color: colors.muted,
    animationName: {
      default: loadingSpin,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: "900ms",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  content: {
    position: "relative",
    display: "grid",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  noteLoadingOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 5,
    display: "grid",
    placeItems: "start center",
    paddingTop: "14px",
    backgroundColor: `color-mix(in srgb, ${colors.canvas} 12%, transparent)`,
    backdropFilter: "blur(1px)",
  },
  noteLoadingPill: {
    display: "inline-flex",
    height: "28px",
    alignItems: "center",
    gap: "7px",
    paddingInline: "11px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: "999px",
    backgroundColor: `color-mix(in srgb, ${colors.elevated} 94%, transparent)`,
    boxShadow: "0 4px 14px rgb(35 33 29 / 10%)",
    color: colors.muted,
    fontSize: "10px",
    fontWeight: 600,
  },
  noteLoadingIcon: {
    width: "13px",
    height: "13px",
    animationName: {
      default: loadingSpin,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: "900ms",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  singlePane: { gridTemplateColumns: "minmax(0, 1fr)" },
  splitPane: (ratio: number) => ({
    gridTemplateColumns: {
      default: `${ratio}fr ${1 - ratio}fr`,
      "@media (max-width: 760px)": "minmax(0, 1fr)",
    },
  }),
  paneContainer: {
    position: "relative",
    display: "grid",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
  },
  pane: {
    position: "relative",
    height: "100%",
    minHeight: {
      default: 0,
      "@media (max-width: 760px)": "calc(100vh - 138px)",
    },
    minWidth: 0,
    overflow: "hidden",
    borderRightWidth: {
      default: "1px",
      "@media (max-width: 760px)": 0,
    },
    borderRightStyle: "solid",
    borderRightColor: colors.border,
    backgroundColor: colors.canvas,
    animationName: {
      default: fadeIn,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: motion.fast,
    animationTimingFunction: motion.ease,
  },
  paneDropActive: {
    boxShadow: `inset 0 0 0 1.5px color-mix(in srgb, ${accents.primary} 55%, transparent)`,
  },
  codeMirrorHost: { height: "100%", minHeight: 0 },
  clipboardFallback: { position: "fixed", left: "-9999px" },
  dropOverlay: {
    position: "absolute",
    inset: "10px 10px 36px",
    zIndex: 2,
    display: "grid",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: `color-mix(in srgb, ${accents.primary} 55%, ${colors.border})`,
    borderRadius: "8px",
    backgroundColor: `color-mix(in srgb, ${accents.soft} 72%, transparent)`,
    color: accents.primary,
    fontSize: "12px",
    fontWeight: 620,
    letterSpacing: 0,
    pointerEvents: "none",
  },
  statusbar: {
    position: "absolute",
    insetInline: 0,
    bottom: 0,
    display: "flex",
    height: "28px",
    alignItems: "center",
    gap: "12px",
    paddingInline: "16px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    backgroundColor: `color-mix(in srgb, ${colors.elevated} 80%, transparent)`,
    boxShadow: "0 -4px 16px rgb(67 58 45 / 3%)",
    color: colors.muted,
    fontSize: "9px",
    backdropFilter: "blur(12px)",
  },
});

export const searchStyles = stylex.create({
  panel: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto auto auto auto",
    alignItems: "center",
    gap: "6px 8px",
    padding: "8px 10px 9px",
  },
  fieldWrap: {
    position: "relative",
    display: "flex",
    minWidth: 0,
    alignItems: "center",
  },
  fieldIcon: {
    position: "absolute",
    top: "50%",
    left: "9px",
    zIndex: 1,
    color: colors.muted,
    pointerEvents: "none",
    transform: "translateY(-50%)",
  },
  svgIcon: {
    width: "14px",
    height: "14px",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  field: {
    width: "100%",
    minWidth: 0,
    height: "28px",
    paddingBlock: 0,
    paddingLeft: "28px",
    paddingRight: "12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: `color-mix(in srgb, ${colors.border} 90%, transparent)`,
      ":hover": colors.border,
      ":focus": `color-mix(in srgb, ${accents.primary} 55%, ${colors.border})`,
    },
    borderRadius: "8px",
    outline: "none",
    backgroundColor: {
      default: `color-mix(in srgb, ${colors.elevated} 88%, ${colors.panel})`,
      ":focus": colors.elevated,
    },
    boxShadow: {
      default: "inset 0 1px rgb(255 255 255 / 36%)",
      ":focus": `0 0 0 3px color-mix(in srgb, ${accents.primary} 14%, transparent)`,
    },
    color: colors.text,
    fontFamily: typography.uiFont,
    fontSize: "12px",
    letterSpacing: 0,
    transitionProperty: "border-color, background-color, box-shadow",
    transitionDuration: "150ms",
    transitionTimingFunction: motion.ease,
    "::placeholder": { color: colors.muted },
  },
  fieldInvalid: {
    borderColor: `color-mix(in srgb, ${colors.danger} 62%, ${colors.border})`,
  },
  count: {
    minWidth: "4.25em",
    color: colors.muted,
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums",
    letterSpacing: 0,
    textAlign: "right",
    whiteSpace: "nowrap",
  },
  countEmpty: { color: `color-mix(in srgb, ${colors.muted} 55%, transparent)` },
  countInvalid: { color: colors.danger },
  group: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
  },
  dividedGroup: {
    marginLeft: "2px",
    paddingLeft: "6px",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: `color-mix(in srgb, ${colors.border} 82%, transparent)`,
  },
  iconButton: {
    display: "grid",
    width: "26px",
    height: "26px",
    placeItems: "center",
    padding: 0,
    borderWidth: 0,
    borderRadius: "6px",
    outline: {
      default: "none",
      ":focus-visible": `2px solid color-mix(in srgb, ${accents.primary} 58%, transparent)`,
    },
    outlineOffset: "1px",
    backgroundColor: {
      default: "transparent",
      ":hover": `color-mix(in srgb, ${colors.elevated} 70%, transparent)`,
    },
    color: {
      default: colors.muted,
      ":hover": colors.text,
    },
    fontFamily: typography.uiFont,
    fontSize: "11px",
    fontWeight: 620,
    letterSpacing: 0,
    lineHeight: 1,
    userSelect: "none",
    transitionProperty: "color, background-color, box-shadow",
    transitionDuration: "150ms",
    transitionTimingFunction: motion.ease,
  },
  toggle: { fontFamily: typography.monoFont, fontSize: "10px" },
  toggleActive: {
    backgroundColor: `color-mix(in srgb, ${accents.soft} 88%, transparent)`,
    color: colors.text,
    boxShadow: `inset 0 0 0 1px color-mix(in srgb, ${colors.border} 72%, transparent)`,
  },
  closeButton: {
    marginLeft: "2px",
    color: `color-mix(in srgb, ${colors.muted} 88%, transparent)`,
  },
  replaceActions: {
    gridColumn: "2 / -1",
    justifyContent: "flex-end",
    gap: "6px",
  },
  action: {
    display: "inline-flex",
    minWidth: 0,
    height: "26px",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: "10px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: `color-mix(in srgb, ${colors.border} 88%, transparent)`,
      ":hover": colors.border,
    },
    borderRadius: "8px",
    outline: {
      default: "none",
      ":focus-visible": `2px solid color-mix(in srgb, ${accents.primary} 58%, transparent)`,
    },
    outlineOffset: "1px",
    backgroundColor: {
      default: `color-mix(in srgb, ${colors.panel} 82%, ${colors.elevated})`,
      ":hover": colors.panel,
    },
    color: {
      default: `color-mix(in srgb, ${colors.text} 88%, ${colors.muted})`,
      ":hover": colors.text,
    },
    fontFamily: typography.uiFont,
    fontSize: "11px",
    fontWeight: 550,
    letterSpacing: 0,
    lineHeight: 1,
    userSelect: "none",
    cursor: "pointer",
  },
});

export const wikiStyles = stylex.create({
  completion: {
    position: "absolute",
    zIndex: 5,
    minWidth: "220px",
    maxWidth: "320px",
    marginTop: "6px",
    padding: "4px",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${colors.border} 88%, transparent)`,
    borderRadius: "8px",
    backgroundColor: colors.elevated,
    boxShadow: "0 10px 28px rgb(40 36 30 / 12%)",
    pointerEvents: "auto",
  },
  option: {
    display: "grid",
    width: "100%",
    padding: "6px 8px",
    borderWidth: 0,
    borderRadius: "8px",
    backgroundColor: {
      default: "transparent",
      ":hover": `color-mix(in srgb, ${accents.soft} 80%, transparent)`,
    },
    color: "inherit",
    fontFamily: "inherit",
    fontSize: "inherit",
    textAlign: "left",
    cursor: "pointer",
    appearance: "none",
  },
  optionActive: {
    backgroundColor: `color-mix(in srgb, ${accents.soft} 80%, transparent)`,
  },
  title: { display: "block", fontSize: "12px", fontWeight: 600 },
  path: {
    display: "block",
    marginTop: "1px",
    color: colors.muted,
    fontSize: "10px",
    textDecorationLine: "underline",
    textDecorationStyle: "dotted",
    textUnderlineOffset: "2px",
    textDecorationColor: `color-mix(in srgb, ${colors.muted} 55%, transparent)`,
  },
  pathActive: {
    color: `color-mix(in srgb, ${colors.text} 62%, ${colors.muted})`,
    textDecorationColor: `color-mix(in srgb, ${accents.primary} 45%, transparent)`,
  },
});
