import * as stylex from "@stylexjs/stylex";
import {
  accents,
  colors,
  media,
  motion,
  typography,
} from "../../styles/tokens.stylex";

export const settingsStyles = stylex.create({
  dialog: {
    maxWidth: "860px",
    maxHeight: {
      default: "min(760px, calc(100vh - 40px))",
      [media.mobile]: "calc(100vh - 20px)",
    },
    overflow: "hidden",
    borderRadius: {
      default: "14px",
      [media.mobile]: "12px",
    },
  },
  dialogHeader: {
    height: "48px",
    paddingTop: 0,
    paddingRight: "10px",
    paddingBottom: 0,
    paddingLeft: "22px",
  },
  dialogBody: {
    padding: 0,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: {
      default: "176px minmax(0, 1fr)",
      [media.mobile]: "1fr",
    },
    height: {
      default: "min(620px, calc(100vh - 98px))",
      [media.mobile]: "calc(100vh - 78px)",
    },
    minHeight: {
      default: "520px",
      [media.mobile]: 0,
    },
  },
  sidebar: {
    display: {
      default: "flex",
      [media.mobile]: "block",
    },
    minHeight: 0,
    flexDirection: "column",
    borderRightWidth: {
      default: "1px",
      [media.mobile]: 0,
    },
    borderRightStyle: "solid",
    borderRightColor: `color-mix(in srgb, ${colors.border} 88%, transparent)`,
    borderBottomWidth: {
      default: 0,
      [media.mobile]: "1px",
    },
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundImage: `linear-gradient(180deg, color-mix(in srgb, ${colors.panel} 93%, ${colors.elevated}), ${colors.panel})`,
    backgroundColor: colors.panel,
    padding: {
      default: "18px 12px 14px",
      [media.mobile]: "9px 10px",
    },
  },
  navigation: {
    display: "grid",
    gridTemplateColumns: {
      default: null,
      [media.mobile]: "repeat(5, minmax(104px, 1fr))",
    },
    gap: {
      default: "4px",
      [media.mobile]: "5px",
    },
    overflowX: {
      default: "visible",
      [media.mobile]: "auto",
    },
  },
  navItem: {
    appearance: "none",
    display: "grid",
    width: "100%",
    height: "36px",
    gridTemplateColumns: {
      default: "15px minmax(0, 1fr)",
      [media.mobile]: "15px auto",
    },
    alignItems: "center",
    justifyContent: {
      default: "normal",
      [media.mobile]: "center",
    },
    gap: "8px",
    borderWidth: 0,
    borderRadius: "7px",
    paddingBlock: 0,
    paddingInline: "8px",
    backgroundColor: {
      default: "transparent",
      ":hover": `color-mix(in srgb, ${colors.elevated} 54%, transparent)`,
    },
    color: {
      default: `color-mix(in srgb, ${colors.text} 72%, ${colors.muted})`,
      ":hover": colors.text,
    },
    cursor: "pointer",
    fontFamily: typography.uiFont,
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: 1,
    letterSpacing: 0,
    textAlign: "left",
    transitionDuration: {
      default: "150ms",
      [media.reducedMotion]: "0s",
    },
    transitionProperty: "color, background-color, box-shadow",
    transitionTimingFunction: motion.ease,
  },
  navItemActive: {
    backgroundColor: `color-mix(in srgb, ${accents.soft} 76%, ${colors.panel})`,
    color: colors.text,
    fontWeight: 600,
    boxShadow: `inset 0 0 0 1px color-mix(in srgb, ${accents.primary} 9%, transparent)`,
  },
  navIcon: {
    width: "15px",
    height: "15px",
    strokeWidth: 1.8,
  },
  navIconActive: {
    color: accents.primary,
  },
  resetButton: {
    display: {
      default: "inline-flex",
      [media.mobile]: "none",
    },
    width: "100%",
    height: "36px",
    marginTop: "auto",
    justifyContent: "flex-start",
    gap: "9px",
    borderRadius: "8px",
    padding: "0 12px",
    color: colors.muted,
    fontSize: "12px",
    fontWeight: 500,
  },
  smallIcon: {
    width: "15px",
    height: "15px",
    strokeWidth: 1.8,
  },
  content: {
    minWidth: 0,
    overflow: "auto",
    overscrollBehavior: "contain",
    backgroundColor: colors.elevated,
  },
  section: {
    padding: {
      default: "0 20px 24px",
      [media.mobile]: "0 16px 24px",
    },
  },
  row: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(160px, 1fr) auto",
      "@media (max-width: 640px)": "1fr",
    },
    alignItems: "center",
    gap: {
      default: "24px",
      "@media (max-width: 640px)": "8px",
    },
    minHeight: "59px",
    padding: {
      default: "10px 0",
      [media.mobile]: "12px 0",
    },
    borderTopWidth: {
      default: 0,
      ":is([data-settings-row] + [data-settings-row])": "1px",
    },
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in srgb, ${colors.border} 72%, transparent)`,
  },
  rowCopy: {
    minWidth: 0,
  },
  rowLabel: {
    color: colors.text,
    fontSize: "12px",
    fontWeight: 620,
    lineHeight: 1.35,
    letterSpacing: 0,
  },
  rowDescription: {
    maxWidth: "270px",
    margin: 0,
    marginTop: "4px",
    color: colors.muted,
    fontSize: "10px",
    lineHeight: 1.5,
  },
  rowControl: {
    display: "flex",
    minWidth: 0,
    width: {
      default: "auto",
      [media.mobile]: "100%",
    },
    justifyContent: {
      default: "flex-end",
      "@media (max-width: 640px)": "flex-start",
    },
  },
  select: {
    width: {
      default: "auto",
      [media.mobile]: "100%",
    },
  },
  swatches: {
    display: "flex",
    alignItems: "center",
    flexWrap: {
      default: "nowrap",
      [media.mobile]: "wrap",
    },
    gap: "9px",
  },
  swatch: {
    appearance: "none",
    display: "grid",
    width: "25px",
    height: "25px",
    placeItems: "center",
    borderWidth: "3px",
    borderStyle: "solid",
    borderColor: colors.elevated,
    borderRadius: "999px",
    color: "#ffffff",
    cursor: "pointer",
    transform: {
      default: "none",
      ":hover": "translateY(-1px) scale(1.04)",
      [media.reducedMotion]: "none",
    },
    transitionDuration: {
      default: "150ms",
      [media.reducedMotion]: "0s",
    },
    transitionProperty: "transform, box-shadow",
    transitionTimingFunction: motion.ease,
  },
  swatchColor: (color: string) => ({
    backgroundColor: color,
    boxShadow: `0 0 0 1px color-mix(in srgb, ${color} 30%, ${colors.border})`,
  }),
  swatchSelected: (color: string) => ({
    boxShadow: `0 0 0 2px ${colors.elevated}, 0 0 0 4px ${color}`,
  }),
  swatchIcon: {
    width: "12px",
    height: "12px",
    strokeWidth: 3,
  },
  rangeControl: {
    display: "grid",
    width: {
      default: "auto",
      [media.mobile]: "100%",
    },
    gridTemplateColumns: {
      default: "142px 38px",
      [media.mobile]: "minmax(120px, 1fr) 38px",
    },
    alignItems: "center",
    gap: "12px",
  },
  range: {
    width: {
      default: "142px",
      [media.mobile]: "100%",
    },
    height: "18px",
    margin: 0,
    appearance: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    "::-webkit-slider-runnable-track": {
      height: "4px",
      borderRadius: "999px",
      backgroundImage: `linear-gradient(90deg, ${accents.primary} 0 var(--settings-range-progress), color-mix(in srgb, ${colors.border} 84%, ${colors.panel}) var(--settings-range-progress) 100%)`,
    },
    "::-webkit-slider-thumb": {
      width: "15px",
      height: "15px",
      marginTop: "-5.5px",
      appearance: "none",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: `color-mix(in srgb, ${accents.primary} 70%, ${colors.border})`,
      borderRadius: "999px",
      backgroundColor: colors.elevated,
      boxShadow: "0 1px 4px rgb(44 38 30 / 18%)",
    },
    "::-moz-range-track": {
      height: "4px",
      borderRadius: "999px",
      backgroundColor: `color-mix(in srgb, ${colors.border} 84%, ${colors.panel})`,
    },
    "::-moz-range-progress": {
      height: "4px",
      borderRadius: "999px",
      backgroundColor: accents.primary,
    },
    "::-moz-range-thumb": {
      width: "15px",
      height: "15px",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: `color-mix(in srgb, ${accents.primary} 70%, ${colors.border})`,
      borderRadius: "999px",
      backgroundColor: colors.elevated,
      boxShadow: "0 1px 4px rgb(44 38 30 / 18%)",
    },
  },
  rangeProgress: (progress: string) => ({
    "--settings-range-progress": progress,
  }),
  rangeValue: {
    color: colors.muted,
    fontSize: "10px",
    fontVariantNumeric: "tabular-nums",
    textAlign: "right",
  },
  previewBlock: {
    marginTop: "18px",
  },
  overline: {
    color: accents.primary,
    fontSize: "9px",
    fontWeight: 750,
    lineHeight: 1,
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  previewLabel: {
    display: "block",
    margin: "0 0 9px 2px",
    color: colors.muted,
  },
  previewCard: {
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${colors.border} 90%, transparent)`,
    borderRadius: "8px",
    backgroundImage: `linear-gradient(135deg, color-mix(in srgb, ${colors.panel} 62%, transparent), transparent 58%)`,
    backgroundColor: colors.canvas,
    padding: "18px 20px",
    boxShadow: "inset 0 1px rgb(255 255 255 / 36%)",
  },
  previewHeading: {
    margin: 0,
    color: colors.text,
    fontFamily: {
      default: "inherit",
      ':is([data-body-font="serif"] *)': typography.serifFont,
    },
    fontSize: `calc(${typography.bodySize} + 2px)`,
    fontWeight: 720,
    letterSpacing: 0,
  },
  previewBody: {
    maxWidth: "510px",
    margin: 0,
    marginTop: "7px",
    color: `color-mix(in srgb, ${colors.text} 78%, ${colors.muted})`,
    fontFamily: {
      default: "inherit",
      ':is([data-body-font="serif"] *)': typography.serifFont,
    },
    fontSize: `calc(${typography.bodySize} - 2px)`,
    lineHeight: typography.lineHeight,
  },
  previewTags: {
    display: "flex",
    gap: "6px",
    marginTop: "13px",
  },
  badge: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${colors.border} 82%, transparent)`,
    borderRadius: "999px",
    backgroundColor: `color-mix(in srgb, ${colors.elevated} 72%, transparent)`,
    padding: "3px 8px",
    color: colors.muted,
    fontSize: "9px",
  },
  about: {
    display: "grid",
    minHeight: "100%",
    placeItems: "center",
    alignContent: "center",
    padding: "48px",
    textAlign: "center",
  },
  aboutMark: {
    display: "block",
    width: "64px",
    height: "64px",
    filter: `drop-shadow(0 10px 20px color-mix(in srgb, ${accents.primary} 24%, transparent))`,
  },
  aboutKicker: {
    marginTop: "22px",
  },
  aboutTitle: {
    margin: 0,
    marginTop: "9px",
    fontSize: "25px",
    fontWeight: 760,
    letterSpacing: 0,
  },
  aboutBody: {
    maxWidth: "330px",
    margin: 0,
    marginTop: "8px",
    color: colors.muted,
    fontSize: "12px",
    lineHeight: 1.7,
  },
  aboutMeta: {
    display: "flex",
    gap: "7px",
    marginTop: "20px",
  },
  aboutLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "18px",
    color: {
      default: colors.muted,
      ":hover": colors.text,
      ":focus-visible": colors.text,
    },
    fontSize: "12px",
    fontWeight: 550,
    letterSpacing: 0,
    textDecoration: "none",
    outline: {
      default: null,
      ":focus-visible": "none",
    },
    transitionDuration: "150ms",
    transitionProperty: "color",
    transitionTimingFunction: motion.ease,
  },
  aboutLinkIcon: {
    width: "14px",
    height: "14px",
  },
  aiSection: {
    padding: {
      default: "0 24px 30px",
      [media.mobile]: "0 16px 24px",
    },
  },
  aiIntro: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto",
      "@media (max-width: 640px)": "1fr",
    },
    alignItems: "start",
    gap: "12px",
    padding: "24px 0 20px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: `color-mix(in srgb, ${colors.border} 72%, transparent)`,
  },
  aiIntroCopy: {
    minWidth: 0,
  },
  aiTitle: {
    margin: 0,
    color: colors.text,
    fontSize: "19px",
    fontWeight: 740,
    letterSpacing: 0,
    lineHeight: 1.25,
  },
  aiDescription: {
    maxWidth: "520px",
    margin: 0,
    marginTop: "7px",
    color: colors.muted,
    fontSize: "11px",
    lineHeight: 1.6,
  },
  aiStatus: {
    display: "inline-flex",
    flexShrink: 0,
    alignItems: "center",
    gap: "7px",
    marginTop: "1px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${colors.border} 88%, transparent)`,
    borderRadius: "999px",
    backgroundColor: `color-mix(in srgb, ${colors.panel} 72%, transparent)`,
    padding: "6px 9px",
    color: colors.muted,
    fontSize: "10px",
    whiteSpace: "nowrap",
    "@media (max-width: 640px)": {
      gridColumn: "2",
      justifySelf: "start",
      marginTop: "4px",
    },
  },
  aiStatusEnabled: {
    borderColor: `color-mix(in srgb, #3e9b73 35%, ${colors.border})`,
    backgroundColor: `color-mix(in srgb, #3e9b73 9%, ${colors.elevated})`,
    color: `color-mix(in srgb, #3e9b73 70%, ${colors.text})`,
  },
  aiStatusDot: (active: boolean) => ({
    width: "6px",
    height: "6px",
    borderRadius: "999px",
    backgroundColor: active ? "#3e9b73" : colors.muted,
    boxShadow: active ? "0 0 0 3px rgb(62 155 115 / 14%)" : "none",
  }),
  aiConnection: {
    marginTop: "20px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${colors.border} 88%, transparent)`,
    borderRadius: "8px",
    backgroundColor: `color-mix(in srgb, ${colors.panel} 38%, ${colors.elevated})`,
    boxShadow: "inset 0 1px rgb(255 255 255 / 28%)",
    overflow: "hidden",
  },
  aiConnectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    minHeight: "58px",
    padding: "0 16px",
    backgroundColor: `color-mix(in srgb, ${colors.panel} 62%, ${colors.elevated})`,
  },
  aiConnectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: colors.text,
    fontSize: "12px",
    fontWeight: 650,
  },
  aiConnectionIcon: {
    width: "16px",
    height: "16px",
    color: accents.primary,
    strokeWidth: 1.8,
  },
  aiField: {
    display: "grid",
    gridTemplateColumns: "minmax(150px, 0.72fr) minmax(260px, 1.28fr)",
    alignItems: "center",
    gap: "24px",
    minHeight: "68px",
    margin: "0 16px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in srgb, ${colors.border} 70%, transparent)`,
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
      gap: "7px",
      padding: "12px 0",
    },
  },
  aiFieldLabel: {
    color: colors.text,
    fontSize: "11px",
    fontWeight: 600,
  },
  aiFieldHint: {
    maxWidth: "220px",
    margin: 0,
    marginTop: "3px",
    color: colors.muted,
    fontSize: "9px",
    lineHeight: 1.45,
  },
  aiFieldControl: {
    minWidth: 0,
    width: "100%",
  },
  aiSecretControl: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  aiSecretIcon: {
    position: "absolute",
    left: "11px",
    zIndex: 1,
    width: "14px",
    height: "14px",
    color: colors.muted,
    pointerEvents: "none",
  },
  aiSecretInput: {
    paddingLeft: "33px",
    paddingRight: "40px",
  },
  aiSecretToggle: {
    position: "absolute",
    right: 0,
    width: "32px",
    height: "32px",
    minWidth: 0,
    color: colors.muted,
  },
  aiSecretToggleIcon: {
    width: "14px",
    height: "14px",
  },
  aiPrivacyNote: {
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr)",
    gap: "8px",
    padding: "11px 16px 13px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in srgb, ${colors.border} 70%, transparent)`,
    color: colors.muted,
    fontSize: "9px",
    lineHeight: 1.5,
  },
  aiPrivacyIcon: {
    width: "14px",
    height: "14px",
    marginTop: "1px",
    color: accents.primary,
    strokeWidth: 1.8,
  },
  aiModelHeader: {
    display: "flex",
    alignItems: "end",
    justifyContent: "space-between",
    gap: "16px",
    marginTop: "24px",
  },
  aiModelHeading: {
    margin: 0,
    color: colors.text,
    fontSize: "14px",
    fontWeight: 700,
  },
  aiModelHint: {
    maxWidth: "420px",
    margin: 0,
    marginTop: "4px",
    color: colors.muted,
    fontSize: "9px",
    lineHeight: 1.45,
  },
  aiModelReadiness: {
    display: "inline-flex",
    flexShrink: 0,
    alignItems: "center",
    gap: "5px",
    color: colors.muted,
    fontSize: "9px",
    whiteSpace: "nowrap",
  },
  aiReadinessIcon: {
    width: "13px",
    height: "13px",
  },
  aiModelReadinessReady: {
    color: "#3e9b73",
  },
  aiModelGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "12px",
    marginTop: "12px",
    "@media (max-width: 700px)": {
      gridTemplateColumns: "1fr",
    },
  },
  aiModelCard: {
    minWidth: 0,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${colors.border} 88%, transparent)`,
    borderRadius: "8px",
    backgroundColor: `color-mix(in srgb, ${colors.canvas} 78%, ${colors.elevated})`,
    padding: "14px",
    boxShadow: "inset 0 1px rgb(255 255 255 / 24%)",
  },
  aiModelIcon: {
    width: "16px",
    height: "16px",
    color: accents.primary,
    strokeWidth: 1.8,
  },
  aiModelCardTitle: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    color: colors.text,
    fontSize: "11px",
    fontWeight: 650,
  },
  aiModelDescription: {
    minHeight: "40px",
    margin: 0,
    marginTop: "7px",
    color: colors.muted,
    fontSize: "9px",
    lineHeight: 1.45,
  },
  aiModelLabel: {
    display: "block",
    marginTop: "11px",
  },
});
