import * as stylex from "@stylexjs/stylex";
import { accents, colors, motion, typography } from "../../styles/tokens.stylex";

const fadeIn = stylex.keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 },
});

export const graphCardMarker = stylex.defineMarker();

export const graphStyles = stylex.create({
  view: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    backgroundColor: colors.canvas,
  },
  header: {
    display: "flex",
    minHeight: "48px",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    paddingBlock: "6px",
    paddingInline: "16px",
  },
  minWidth: { minWidth: 0 },
  heading: {
    overflow: "hidden",
    color: colors.text,
    fontSize: "13px",
    fontWeight: 600,
    letterSpacing: 0,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  subtitle: {
    overflow: "hidden",
    color: colors.muted,
    fontSize: "11px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerActions: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "8px",
  },
  icon: { width: "16px", height: "16px" },
  orphanLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: colors.muted,
    fontSize: "11px",
  },
  stage: {
    position: "relative",
    minHeight: 0,
    flex: 1,
    overflow: "hidden",
    cursor: {
      default: "grab",
      ":active": "grabbing",
      ':is([data-graph-cursor="pointer"])': "pointer",
      ':is([data-graph-cursor="grabbing"])': "grabbing",
    },
    userSelect: "none",
    backgroundColor: colors.canvas,
    backgroundImage: `radial-gradient(ellipse 70% 55% at 50% 42%, color-mix(in srgb, ${accents.primary} 5%, transparent), transparent 70%)`,
  },
  emptyOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 10,
    display: "grid",
    placeItems: "center",
    color: colors.muted,
    fontSize: "14px",
    pointerEvents: "none",
  },
  legend: {
    position: "absolute",
    left: "16px",
    bottom: {
      default: "16px",
      "@media (max-width: 860px)": "auto",
    },
    top: {
      default: "auto",
      "@media (max-width: 860px)": "12px",
    },
    zIndex: 3,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "12px 16px",
    maxWidth: {
      default: "min(420px, calc(100% - 320px))",
      "@media (max-width: 860px)": "calc(100% - 32px)",
    },
    margin: 0,
    padding: 0,
    color: colors.muted,
    fontSize: "11px",
    lineHeight: 1,
    listStyle: "none",
    pointerEvents: "none",
  },
  legendItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  swatch: {
    width: "8px",
    height: "8px",
    borderRadius: "999px",
    backgroundColor: `color-mix(in srgb, ${accents.primary} 22%, ${colors.canvas})`,
  },
  swatchSelected: {
    width: "10px",
    height: "10px",
    backgroundColor: accents.primary,
    boxShadow: `0 0 0 3px color-mix(in srgb, ${accents.primary} 16%, transparent)`,
  },
  swatchLinked: { backgroundColor: accents.primary },
  swatchEdge: {
    width: "14px",
    height: "2px",
    borderRadius: "99px",
    backgroundColor: `color-mix(in srgb, ${accents.primary} 82%, transparent)`,
  },
  card: {
    position: "absolute",
    right: "16px",
    bottom: "16px",
    zIndex: 3,
    display: "flex",
    width: "min(280px, calc(100% - 32px))",
    alignItems: "flex-start",
    gap: "8px",
    padding: "11px 12px 11px 13px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: `color-mix(in srgb, ${colors.border} 88%, transparent)`,
      ":hover": colors.border,
    },
    borderRadius: "8px",
    backgroundColor: {
      default: `color-mix(in srgb, ${colors.elevated} 92%, ${colors.panel})`,
      ":hover": colors.elevated,
    },
    boxShadow: "0 12px 32px rgb(40 36 30 / 10%)",
    color: "inherit",
    fontFamily: "inherit",
    fontSize: "inherit",
    textAlign: "left",
    cursor: "pointer",
    appearance: "none",
    transitionProperty: "background-color, border-color, box-shadow",
    transitionDuration: motion.standard,
    transitionTimingFunction: motion.ease,
  },
  cardIcon: {
    width: "16px",
    height: "16px",
    flexShrink: 0,
    marginTop: "2px",
    color: accents.primary,
  },
  cardText: {
    minWidth: 0,
    flex: 1,
    textAlign: "left",
  },
  cardTitle: {
    display: "block",
    overflow: "hidden",
    color: colors.text,
    fontSize: "13px",
    fontWeight: 600,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cardPath: {
    display: "block",
    overflow: "hidden",
    marginTop: "2px",
    color: colors.muted,
    fontSize: "11px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cardMeta: {
    display: "block",
    marginTop: "4px",
    color: colors.muted,
    fontSize: "11px",
  },
  cardGo: {
    width: "14px",
    height: "14px",
    flexShrink: 0,
    marginTop: "2px",
    color: {
      default: colors.muted,
      [stylex.when.ancestor(":hover", graphCardMarker)]: colors.text,
    },
    transitionProperty: "color",
    transitionDuration: motion.standard,
    transitionTimingFunction: motion.ease,
  },
  panel: {
    display: "flex",
    minHeight: 0,
    flex: 1,
    flexDirection: "column",
    animationName: {
      default: fadeIn,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: motion.fast,
    animationTimingFunction: motion.ease,
  },
  stats: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "6px",
    marginInline: "12px",
    marginTop: "10px",
  },
  stat: {
    padding: "8px 8px 7px",
    borderRadius: "8px",
    backgroundColor: `color-mix(in srgb, ${colors.elevated} 70%, ${colors.panel})`,
    textAlign: "center",
  },
  statValue: {
    color: colors.text,
    fontSize: "14px",
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: 1.1,
    fontVariantNumeric: "tabular-nums",
  },
  statLabel: {
    display: "block",
    marginTop: "3px",
    color: colors.muted,
    fontSize: "10px",
  },
  search: {
    position: "relative",
    display: "block",
    marginInline: "12px",
    marginTop: "10px",
  },
  searchIcon: {
    position: "absolute",
    top: "50%",
    left: "10px",
    width: "14px",
    height: "14px",
    color: colors.muted,
    pointerEvents: "none",
    transform: "translateY(-50%)",
  },
  searchInput: {
    height: "32px",
    paddingLeft: "32px",
    borderRadius: "8px",
    boxShadow: "none",
  },
  panelScroller: {
    minHeight: 0,
    flex: 1,
    overflow: "auto",
    padding: "8px 10px 12px",
  },
  panelMessage: {
    padding: "32px 8px",
    color: colors.muted,
    fontSize: "12px",
    textAlign: "center",
  },
  nodeRow: {
    display: "grid",
    width: "100%",
    minHeight: "44px",
    gridTemplateColumns: "16px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "8px",
    paddingInline: "10px",
    borderWidth: 0,
    borderRadius: "8px",
    backgroundColor: {
      default: "transparent",
      ":hover": `color-mix(in srgb, ${colors.elevated} 54%, transparent)`,
    },
    color: {
      default: `color-mix(in srgb, ${colors.text} 78%, ${colors.muted})`,
      ":hover": colors.text,
    },
    fontFamily: "inherit",
    textAlign: "left",
    cursor: "pointer",
    appearance: "none",
  },
  nodeRowActive: {
    backgroundColor: `color-mix(in srgb, ${accents.soft} 76%, ${colors.panel})`,
    color: colors.text,
  },
  nodeIcon: {
    width: "14px",
    height: "14px",
    color: colors.muted,
  },
  nodeTitle: {
    display: "block",
    overflow: "hidden",
    color: colors.text,
    fontSize: "12px",
    fontWeight: 500,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  nodePath: {
    display: "block",
    overflow: "hidden",
    color: colors.muted,
    fontSize: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  degree: {
    color: colors.muted,
    fontSize: "10px",
    fontVariantNumeric: "tabular-nums",
  },
  canvas: {
    display: "block",
    width: "100%",
    height: "100%",
    touchAction: "none",
  },
  labels: {
    position: "absolute",
    inset: 0,
    zIndex: 2,
    overflow: "hidden",
    pointerEvents: "none",
  },
  label: {
    position: "absolute",
    top: 0,
    left: 0,
    display: "-webkit-box",
    width: "112px",
    overflow: "hidden",
    padding: 0,
    borderWidth: 0,
    appearance: "none",
    backgroundColor: "transparent",
    color: `color-mix(in srgb, ${colors.text} 88%, ${colors.muted})`,
    fontFamily: typography.uiFont,
    fontSize: "11px",
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: 1.35,
    textAlign: "center",
    pointerEvents: "auto",
    cursor: "pointer",
    userSelect: "none",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    wordBreak: "break-word",
  },
  labelNeighbor: { color: colors.text, fontWeight: 550 },
  labelActive: { color: colors.text, fontWeight: 650 },
  labelMuted: {
    color: `color-mix(in srgb, ${colors.muted} 72%, ${colors.text})`,
    fontWeight: 450,
  },
});
